-- GOVERNMENT ABAC FUNCTIONS
USE CATALOG apscat; USE SCHEMA government;

CREATE OR REPLACE FUNCTION mask_ssn_last4(ssn STRING) RETURNS STRING
COMMENT 'SSN masking' RETURN CASE WHEN ssn IS NULL THEN ssn ELSE CONCAT('XXX-XX-', RIGHT(REPLACE(ssn, '-', ''), 4)) END;

CREATE OR REPLACE FUNCTION mask_license_plate_partial(plate STRING) RETURNS STRING
COMMENT 'Plate partial' RETURN CASE WHEN plate IS NULL THEN plate ELSE CONCAT('***-', RIGHT(plate, 4)) END;

CREATE OR REPLACE FUNCTION mask_address_zip_only(address STRING, zip STRING) RETURNS STRING
COMMENT 'ZIP only' RETURN COALESCE(zip, '***');

CREATE OR REPLACE FUNCTION mask_tax_amount_bucket(amt DECIMAL(12,2)) RETURNS STRING
COMMENT 'Tax ranges' RETURN CASE WHEN amt IS NULL THEN 'Unknown' WHEN amt < 10000 THEN '$0-$10K'
WHEN amt < 50000 THEN '$10K-$50K' WHEN amt < 100000 THEN '$50K-$100K' ELSE '$100K+' END;

CREATE OR REPLACE FUNCTION mask_citizen_id_hash(id STRING) RETURNS STRING
COMMENT 'Deterministic' RETURN CONCAT('CIT_', SUBSTRING(SHA2(id, 256), 1, 12));

SELECT '✅ Government functions created!' AS status;
